title: Into the Unknown
description: A Westmarch GLOG Hack
baseurl: "/westmarch-landol" # the subpath of your site, e.g. /blog
url: "https://owl73.github.io" # the base hostname & protocol for your site, e.g. http://example.com



remote_theme: pmarsceill/just-the-docs
color_scheme: dark
